#!/bin/bash
#                                                                    2020-03-12
#    Installa bugy/script-server sul PC
#                                                                  Version="1.00"
wget -O ${HOME}/managerdirs.tar.gz https://github.com/fpirri/gothings-pc-manager/raw/main/managerdirs.tar.gz
sudo tar xpf "${HOME}/managerdirs.tar.gz" -C "${HOME}";
./dockrepo/install_pc_manager
#
#
#
#===============================================================================
#                                                                 Organizzazione
#  download latest manager da repository
#  installa sul PC
#
################################################################################
#
#==============================================================================
echo
echo "============================================================ PC GOTHINGS"
echo
echo "      GOTHINGS boot loader for PC Manager"
echo
echo "============================================================ version 1.00"
echo
#
################################################################################
#
echo
echo "No errors?"
echo
echo "Congratulations! You have installed your PC Manager"
echo
echo "Open a browser in this PC and go to the site:"
echo "  localhost:5000"
echo
echo "You may like to try the script 'Ping your raspi'"
echo
echo "Please have a look at the documentation at 'www.gothings.org'"
echo

