#!/bin/bash
#                                                                    2020-03-12
#    Installa bugy/script-server sul PC
#
################################################################################
#                                                              exec manager-init
#  questo file va scaricato dal repo ed eseguito sul PC
#  oneliner:
#    wget -O ${HOME}/manager-init https://github.com/fpirri/gothings-pc-manager/raw/main/manager-init && source ${HOME}/manager-init
#
################################################################################
#                                                                       set dirs
echo
echo "Verify directory structure ..."
# la prima volta non ci sono i dirs, creiamoli !
#
# ~/dockrepo/
  if [ ! -d "~/dockrepo" ]; then
    mkdir "dockrepo"
  fi
# ~/dockrepo/pc-manager/
  if [ ! -d "~/dockrepo/pc-manager/" ]; then
    mkdir "~/dockrepo/pc-manager/"
  fi
# verify
cd ~/dockrepo/pc-manager/
Result=$?
if [ $Result -gt 0 ]
then
  echo "$Result error - cannot cd into pc-manager directory"
  exit 33
fi
echo "now in pc-manager directory"
#
################################################################################
#                                          download latest manager da repository
#
wget -O ${HOME}/managerdirs.tar.gz https://github.com/fpirri/gothings-pc-manager/raw/main/managerdirs.tar.gz
#
################################################################################
#                                                             expand in dockrepo
#
sudo tar xpf "${HOME}/managerdirs.tar.gz" -C "${HOME}"
#
#
################################################################################
#                                                                installa sul PC
#
./dockrepo/pc-manager/install_pc_manager
#
################################################################################
#                                                                Avvisa l'utente
#
echo
echo "============================================================ PC GOTHINGS"
echo
echo "      GOTHINGS boot loader for PC Manager"
echo
echo "============================================================ version 1.00"
echo
echo
echo "No errors?"
echo
echo "Congratulations! You have installed your PC Manager"
echo
echo "Open a browser in this PC and go to the site:"
echo "  localhost:5000"
echo
echo "You may like to try the script 'Ping your raspi'"
echo
echo "Please have a look at the documentation at 'www.gothings.org'"
echo
