#!/bin/bash
#                                                                    2022-01-31
                                                                 Version="02.01"
#    Installa bugy/script-server sul PC
#
################################################################################
#                                                              exec manager-init
#  questo file va scaricato dal repo ed eseguito sul PC
#  oneliner:
#    wget -O ${HOME}/pc-manager-init https://github.com/fpirri/gothings-pc-manager/raw/main/pc-manager-init && bash ${HOME}/pc-manager-init
#
################################################################################
#                                                                       set dirs
echo
echo "Verify directory structure ..."
# la prima volta non ci sono i dirs, creiamoli !
#
# ~/dockrepo/
Dockrepo="/$HOME/dockrepo/"
  if [ ! -d "$Dockrepo" ]; then
    mkdir "dockrepo"
  fi
# ~/dockrepo/pc-manager/
ManagerDir="${Dockrepo}pc-manager"
  if [ ! -d "$ManagerDir" ]; then
    mkdir "$ManagerDir"
  fi
# ~/dockrepo/temp/
TempDir="${Dockrepo}temp"
  if [ ! -d "$TempDir" ]; then
    mkdir "$TempDir"
  fi
# verify
cd $TempDir
Result=$?
if [ $Result -gt 0 ]
then
  echo "$Result error - cannot cd into temp directory"
  exit 33
fi
echo "now in temp directory"
#
################################################################################
#                                          download latest manager da repository
#
wget -O ${TempDir}/pc-managerdirs.tar.gz https://github.com/fpirri/gothings-pc-manager/raw/main/pc-managerdirs.tar.gz
#
################################################################################
#                                                             expand in dockrepo
#
sudo tar xpf "${TempDir}/managerdirs.tar.gz" -C "${HOME}"
#
#
################################################################################
#                                                                installa sul PC
#
cd /$HOME/dockrepo/pc-manager/
Result=$?
if [ $Result -gt 0 ]
then
  echo "$Result error - cannot cd into pc-manager directory"
  exit 35
fi
echo "now in pc-manager directory"
./dockrepo/pc-manager/install_pc_manager
#
################################################################################
#                                                                Avvisa l'utente
#
echo
echo "============================================================ PC GOTHINGS"
echo
echo "      GOTHINGS boot loader for PC Manager"
echo
echo "============================================================ $Version"
echo
echo
echo "No errors?"
echo
echo "Congratulations! You have installed your PC Manager"
echo
echo "Open a browser in this PC and go to the site:"
echo "  localhost:5000"
echo
echo "You may like to try the script 'Ping your raspi'"
echo
echo "Please have a look at the documentation at 'www.gothings.org'"
echo
